<main class="container">
  <div class="gallery">
    <a href="#">
      <div class="gallery_image"></div>
      <h3>This is the title</h3>
      <p>This is the description</p>
      <small>this is the Url</small>
    </a>

    <a href="#">
      <div class="gallery_image"></div>
      <h3>This is the title</h3>
      <p>This is the description</p>
      <small>this is the Url</small>
    </a>

    <a href="#">
      <div class="gallery_image"></div>
      <h3>This is the title</h3>
      <p>This is the description</p>
      <small>this is the Url</small>
    </a>

    <a href="#">
      <div class="gallery_image"></div>
      <h3>This is the title</h3>
      <p>This is the description</p>
      <small>this is the Url</small>
    </a>


  </div>
</main>