version: "3"

services:
  #nginx
  qsserver:
    container_name: qsserver
    image: nginx:stable-alpine
    restart: always
    ports:
      - "6082:80"
    working_dir: /var/www/html
    volumes:
      - ../html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - quicknet

  #php
  qsapp:
    container_name: qsapp
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    working_dir: /var/www/html
    volumes:
      - ../html:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - quicknet

  #db
  qsdb:
    container_name: qsdb
    platform: linux/x86_64
    image: mysql:8
    # ports:
    #   - 9586:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - qsdata:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_DATABASE: quickstart
      MYSQL_ROOT_PASSWORD: r00tadmin
    networks:
      - quicknet

  qsadmin:
    container_name: qsadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: qsdb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 6084:80
    networks:
      - quicknet

volumes:
  qsdata:
    driver: local

networks:
  quicknet:
    name: quicknet
