<!-- THE LOGIN PAGE -->
<main class="container">

  <h1>LOGIN</h1>
  <?php if (!empty($data['errorList'])) : ?>
  <div>
    <p>Errors:</p>
    <ul>
      <?php foreach ($data['errorList'] as $value) : ?>
      <li><?= $value ?></li>
      <?php endforeach ?>
    </ul>
  </div>
  <?php endif ?>

  <form class="formContainer" action="" method="POST">
    <label class="email" for="email">Email
      <input type="email" name="email" id="email">
    </label>
    <label class="password" for="password">Password
      <input type="password" name="password" id="password">
    </label>
    <button class="btn btn-fern rad-shadow float" type="submit">SEND</button>
  </form>

</main>