<main>

  <button class="tablink" onclick="openPage('Tables', this, 'brown')" id="defaultOpen">Tables</button>

  <div id="Tables" class="tabcontent">

    <h3>THE WEBSITE SETUP PAGE</h3>
    <form class="formContainer" action="/setup/tables/blog" method="post">
      <div class="group grid grid1">
        <input class="left" type="text" name="blog" id="blog" value="Blog Tables" readonly>
        <input class="right" type="submit" value="Create">
      </div>
    </form>

  </div>

</main>