<main>

  <button class="tablink" onclick="openPage('BlogNew', this, 'brown')" id="defaultOpen">Blog New Post</button>
  <button class="tablink" onclick="openPage('Preview', this, 'brown')">Blog Preview Page</button>

  <div id="BlogNew" class="tabcontent">

    <h3>EDIT BLOG POST ID : <?= $data['id'] ?></h3>
    <form class="formContainer" action="" method="post">
      <input type="text" name="id" id="id" value="<?= $data['id'] ?>" hidden>

      <div class="group grid grid3">
        <label for="author" class="left">Author
          <input type="text" name="author" id="author" value="<?= $data['author'] ?>">
        </label>
        <label for="image_author" class="middle">Author Image Url
          <input type="text" name="image_author" id="image_author" value="<?= $data['image_author'] ?>">
        </label>
        <label for="date_at" class="right">Date
          <input type="text" name="date_at" id="date_at" value="<?= $data['date_at'] ?>">
        </label>
      </div>

      <div class="group grid grid1">
        <label for="title" class="left">Title
          <input type="text" name="title" id="title" value="<?= $data['title'] ?>">
        </label>
        <select id="status" name="status" class="right">
          <option <?= ($data['status'] == 'draft') ? 'selected' : '' ?> value="draft">Draft</option>
          <option <?= ($data['status'] == 'publish') ? 'selected' : '' ?> value="publish">Publish</option>
        </select>
      </div>
      <div class="group grid grid1">
        <label for="slug" class="left">Slug
          <input type="text" name="slug" id="slug" value="<?= $data['slug'] ?>" readonly>
        </label>
        <button type="button" class="right btn btn-fern" onclick="createSlug()">Create Slug</button>
      </div>

      <div class="group grid grid2">
        <label for="image_landscape" class="left">Landscape Image Url
          <input type="text" name="image_landscape" id="image_landscape" value="<?= $data['image_landscape'] ?>">
        </label>
        <label for="image_portrait" class="right">Portrait Image Url
          <input type="text" name="image_portrait" id="image_portrait" value="<?= $data['image_portrait'] ?>">
        </label>
      </div>

      <div class="group grid">
        <label for="description">Description
          <textarea name="description" id="description" cols="30" rows="10"><?= $data['description'] ?></textarea>
        </label>
      </div>
      <div class="group grid">
        <textarea name="content" id="content" cols="30" rows="10"><?= $data['content'] ?></textarea>
      </div>
      <div class="group grid grid1">
        <button class="right btn btn-fern" style="height: 5em;" type="submit">UPDATE BLOG POST</button>
      </div>
    </form>

  </div>








  <div id="Preview" class="tabcontent">
    <div class="grid4">
      <div class="left card_landscape">
        <div class="card_landscape_image">
          <img src="<?= $data['image_landscape'] ?>" alt="">
        </div>
        <div class="card_landscape_content">

          <h2><?= $data['title'] ?></h2>
          <p class="desc"><?= $data['description'] ?></p>
          <small>
            <span><?= $data['date_at'] ?></span>
            <span><img class="img_author" src="<?= $data['image_author'] ?>" alt="Image Author"
                srcset="Image Author"></span>
            <span><?= $data['author'] ?></span>
            <button href="#" class="card_btn float">Read More</button>
          </small>

        </div>



      </div>

      <div class="right card_portrait">
        <div class="card_portrait_image">
          <img src="<?= $data['image_portrait'] ?>" alt="">
        </div>
        <div class="card_portrait_content">

          <h2><?= $data['title'] ?></h2>
          <p class="desc"><?= $data['description'] ?></p>
          <small>
            <button href="#" class="card_btn float">Read More</button>
          </small>

        </div>

      </div>
    </div>


    <div class="blog">
      <div class="title">
        <h2><?= $data['title'] ?></h2>
        <small>
          <span><?= $data['date_at'] ?></span>
          <span><img class="img_author" src="<?= $data['image_author'] ?>" alt="Image Author"
              srcset="Image Author"></span>
          <span><?= $data['author'] ?></span>
        </small>
      </div>
      <div class="output">
        <?= $data['output'] ?>
      </div>


      <div>
        <textarea name="" id="" cols="30" rows="10"><?= $data['output'] ?></textarea>
      </div>
    </div>













  </div>










</main>