<!DOCTYPE html>
<html lang='en'>

  <head>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Document</title>
    <link rel='icon' href='data:,' />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  </head>

  <body>
    <form action="" method="post">
      <textarea name="content" id="content" cols="30" rows="10"></textarea>
      <input type="submit" value="SAVE">
    </form>


    <script>
    var simplemde = new SimpleMDE({
      element: document.getElementById("content"),
    });
    </script>

  </body>

</html>