<meta charset="<?= $scMetaCharset ?>">
<meta name="google-site-verification" content="<?= $scMetaGoogleSiteVerification ?>">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="<?= $scMetaDescription ?>">
<meta name="Keywords" content="<?= $scMetaKeywords ?>">
<meta name="Copyright" content="<?= $scMetaOgSiteName ?>">


<title><?= $scMetaOgTitle . " | " . $scMetaOgSiteName ?></title>

<link rel='icon' href='data:,' />